[versions]
agp = "8.9.0-alpha04"
android-minSdk = "23"
android-compileSdk = "35"
android-buildToolsVersion = "35.0.0"
android-ndkVersion = "28.0.12674087"
lib-version = "1.0.0-alpha26"

kotlin = "2.1.0"
rules = "1.6.1"
runner = "1.6.2"

[libraries]
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
