[versions]
agp = "8.1.3"
android-minSdk = "21"
android-compileSdk = "34"
app-version = "1.13.1.2431"
kotlin = "1.9.20"
rules = "1.5.0"
runner = "1.5.2"

[libraries]
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
