[versions]
agp = "8.5.0"
android-minSdk = "21"
android-compileSdk = "34"
android-ndkVersion = "27.0.11902837"
lib-version = "1.0.0-alpha18"
kotlin = "2.0.0"
rules = "1.5.0"
runner = "1.5.2"

[libraries]
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
