name: Build TagLib AAR for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Verify Gradle Wrapper
        run: ./gradlew --version

      - name: Build release AAR
        run: ./gradlew clean assembleRelease

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: taglib-release-aar
          path: taglib/build/outputs/aar/taglib-release.aar
